// <auto-generated />
using System;
using ApiProyecto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProyecto.Migrations
{
    [DbContext(typeof(EmpresaDbContext))]
    [Migration("20251021163333_AddSoftDeleteToPersona")]
    partial class AddSoftDeleteToPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiProyecto.Models.Contrato", b =>
                {
                    b.Property<int>("IdContratos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContratos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdContratos"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("FechaFinal")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PersonasIdPersonas")
                        .HasColumnType("int")
                        .HasColumnName("Personas_idPersonas");

                    b.Property<string>("Sueldo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdContratos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PersonasIdPersonas" }, "Personas_idPersonas");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("ApiProyecto.Models.Detalleventum", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDetalleVenta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalleVenta"));

                    b.Property<int?>("Cantidad")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioTotal")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double?>("PrecioUnitario")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<int?>("ProductosIdProductos")
                        .HasColumnType("int")
                        .HasColumnName("Productos_idProductos");

                    b.Property<int?>("VentasIdVentas")
                        .HasColumnType("int")
                        .HasColumnName("Ventas_idVentas");

                    b.HasKey("IdDetalleVenta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProductosIdProductos" }, "Productos_idProductos");

                    b.HasIndex(new[] { "VentasIdVentas" }, "Ventas_idVentas");

                    b.ToTable("detalleventa");
                });

            modelBuilder.Entity("ApiProyecto.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idInventario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<DateTime?>("FechaIngreso")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PrecioTotal")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdInventario")
                        .HasName("PRIMARY");

                    b.ToTable("inventario");
                });

            modelBuilder.Entity("ApiProyecto.Models.Persona", b =>
                {
                    b.Property<int>("IdPersonas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPersonas");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPersonas"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("EstaEliminado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("UsuariosIdUsuarios")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_idUsuarios");

                    b.Property<int?>("UsuariosPersonasIdPersonas")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_Personas_idPersonas");

                    b.HasKey("IdPersonas")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cedula" }, "Cedula")
                        .IsUnique();

                    b.HasIndex(new[] { "UsuariosIdUsuarios" }, "Usuarios_idUsuarios");

                    b.ToTable("personas");
                });

            modelBuilder.Entity("ApiProyecto.Models.Producto", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProductos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProductos"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("InventarioIdInventario")
                        .HasColumnType("int")
                        .HasColumnName("Inventario_idInventario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.HasKey("IdProductos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InventarioIdInventario" }, "Inventario_idInventario");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ApiProyecto.Models.Role", b =>
                {
                    b.Property<int>("IdRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRoles");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRoles"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdRoles")
                        .HasName("PRIMARY");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ApiProyecto.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuarios");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuarios"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("PersonasIdPersonas")
                        .HasColumnType("int")
                        .HasColumnName("Personas_idPersonas");

                    b.Property<int?>("RolesIdRoles")
                        .HasColumnType("int")
                        .HasColumnName("Roles_idRoles");

                    b.HasKey("IdUsuarios")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correo" }, "Correo")
                        .IsUnique();

                    b.HasIndex(new[] { "RolesIdRoles" }, "Roles_idRoles");

                    b.HasIndex(new[] { "PersonasIdPersonas" }, "fk_Usuarios_Personas");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ApiProyecto.Models.Venta", b =>
                {
                    b.Property<int>("IdVentas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVentas");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVentas"));

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<int?>("UsuariosIdUsuarios")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_idUsuarios");

                    b.Property<int?>("UsuariosPersonasIdPersonas")
                        .HasColumnType("int")
                        .HasColumnName("Usuarios_Personas_idPersonas");

                    b.HasKey("IdVentas")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UsuariosPersonasIdPersonas" }, "Usuarios_Personas_idPersonas");

                    b.HasIndex(new[] { "UsuariosIdUsuarios" }, "Usuarios_idUsuarios")
                        .HasDatabaseName("Usuarios_idUsuarios1");

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("ApiProyecto.Models.Contrato", b =>
                {
                    b.HasOne("ApiProyecto.Models.Persona", "PersonasIdPersonasNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("PersonasIdPersonas")
                        .HasConstraintName("contratos_ibfk_1");

                    b.Navigation("PersonasIdPersonasNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Detalleventum", b =>
                {
                    b.HasOne("ApiProyecto.Models.Producto", "ProductosIdProductosNavigation")
                        .WithMany("Detalleventa")
                        .HasForeignKey("ProductosIdProductos")
                        .HasConstraintName("detalleventa_ibfk_2");

                    b.HasOne("ApiProyecto.Models.Venta", "VentasIdVentasNavigation")
                        .WithMany("Detalleventa")
                        .HasForeignKey("VentasIdVentas")
                        .HasConstraintName("detalleventa_ibfk_1");

                    b.Navigation("ProductosIdProductosNavigation");

                    b.Navigation("VentasIdVentasNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Persona", b =>
                {
                    b.HasOne("ApiProyecto.Models.Usuario", "UsuariosIdUsuariosNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("UsuariosIdUsuarios")
                        .HasConstraintName("personas_ibfk_1");

                    b.Navigation("UsuariosIdUsuariosNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Producto", b =>
                {
                    b.HasOne("ApiProyecto.Models.Inventario", "InventarioIdInventarioNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("InventarioIdInventario")
                        .HasConstraintName("productos_ibfk_1");

                    b.Navigation("InventarioIdInventarioNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Usuario", b =>
                {
                    b.HasOne("ApiProyecto.Models.Persona", "PersonasIdPersonasNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("PersonasIdPersonas")
                        .HasConstraintName("fk_Usuarios_Personas");

                    b.HasOne("ApiProyecto.Models.Role", "RolesIdRolesNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolesIdRoles")
                        .HasConstraintName("usuarios_ibfk_1");

                    b.Navigation("PersonasIdPersonasNavigation");

                    b.Navigation("RolesIdRolesNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Venta", b =>
                {
                    b.HasOne("ApiProyecto.Models.Usuario", "UsuariosIdUsuariosNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("UsuariosIdUsuarios")
                        .HasConstraintName("ventas_ibfk_1");

                    b.HasOne("ApiProyecto.Models.Persona", "UsuariosPersonasIdPersonasNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("UsuariosPersonasIdPersonas")
                        .HasConstraintName("ventas_ibfk_2");

                    b.Navigation("UsuariosIdUsuariosNavigation");

                    b.Navigation("UsuariosPersonasIdPersonasNavigation");
                });

            modelBuilder.Entity("ApiProyecto.Models.Inventario", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ApiProyecto.Models.Persona", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Usuarios");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ApiProyecto.Models.Producto", b =>
                {
                    b.Navigation("Detalleventa");
                });

            modelBuilder.Entity("ApiProyecto.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiProyecto.Models.Usuario", b =>
                {
                    b.Navigation("Personas");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ApiProyecto.Models.Venta", b =>
                {
                    b.Navigation("Detalleventa");
                });
#pragma warning restore 612, 618
        }
    }
}
